branches:
  only:
    - master
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn --frozen-lockfile
script:
  - yarn test
  - yarn build:release
cache: yarn
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
  - provider: npm
    email: levy9527@qq.com
    api_key: $NPM_TOKEN
    skip-cleanup: true
after_script:
  - ./notify.sh
